using System.Linq;
using Content.Shared.Humanoid;
using Robust.Shared.Prototypes;
using Content.Shared._DeepLagoon.InteractionPanel;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DeepLagoon.InteractionPanel;

[GenerateTypedNameReferences]
public sealed partial class InteractionPanelWindow : DefaultWindow
{
    private readonly HashSet<string> _available;
    private readonly InteractionPanelActionDefinition[] _standardActions = InteractionPanelActionCatalog.Load(IoCManager.Resolve<IPrototypeManager>());
    private InteractionPanelActionDefinition[] _definitions;
    private readonly HashSet<string> _favorites;
    private readonly bool _self;
    private readonly bool _humanoid;
    private readonly Sex? _userSex;
    private readonly Sex? _targetSex;
    private string _region = "all";
    private readonly HashSet<string> _repeating = new();
    public NetEntity Target { get; }
    public InteractionPanelCustomEditor Editor => CustomEditor;
    public event Action<string>? ActionRequested;
    public event Action<string, bool, float>? RepeatRequested;
    public event Action? PreferencesChanged;
    public float Interval => InteractionPanelActions.ClampInterval(Speed.Value);
    public IEnumerable<string> Favorites => _favorites;

    public InteractionPanelWindow(InteractionPanelPanelEvent data, EntityUid? target, IEnumerable<string> favorites, float interval)
    {
        _definitions = _standardActions;
        RobustXamlLoader.Load(this);
        Stylesheet = InteractionPanelTheme.Create(UserInterfaceManager.Stylesheet);
        Tabs.SetTabTitle(0, Loc.GetString("dl-interaction-panel-tab-actions"));
        Tabs.SetTabTitle(1, Loc.GetString("dl-interaction-panel-tab-custom"));
        SelfLabel.Modulate = RegionLabel.Modulate = InteractionPanelAppearance.AccentText;
        DebugLabel.Modulate = InteractionPanelAppearance.DebugText;
        CountLabel.Modulate = StatusLabel.Modulate = InteractionPanelAppearance.MutedText;
        Target = data.Target;
        _self = data.Self;
        _humanoid = data.Humanoid;
        _userSex = data.UserSex; _targetSex = data.TargetSex;
        BodySelector.Visible = RegionLabel.Visible = AllRegions.Visible = RegionFilter.Visible = _humanoid;
        _available = data.Actions.ToHashSet();
        _favorites = favorites.ToHashSet();
        Title = Loc.GetString("dl-interaction-panel-title", ("name", data.Name));
        CharacterName.Text = data.Name;
        SelfLabel.Visible = _self;
        DebugLabel.Visible = data.DebugPreferences;
        // Меняем фон только этого окна, не затрагивая глобальную тему.
        foreach (var panel in Children.OfType<PanelContainer>()) panel.PanelOverride = new InteractionPanelRoundedStyle(InteractionPanelAppearance.WindowTop, 14, 0) { BottomColor = InteractionPanelAppearance.WindowBottom };
        PreviewPanel.PanelOverride = new InteractionPanelRoundedStyle(InteractionPanelAppearance.CharacterPanel, 12, 2);
        Preview.SetEntity(target);
        Preview.Stretch = SpriteView.StretchMode.Fill;
        Preview.OverrideDirection = Direction.South;
        for (var i = 0; i < InteractionPanelBodySelector.Regions.Length; i++)
            RegionFilter.AddItem(Loc.GetString($"dl-interaction-panel-body-{InteractionPanelBodySelector.Regions[i]}"), i);
        RegionFilter.OnItemSelected += args => SelectRegion(InteractionPanelBodySelector.Regions[args.Id]);
        BodySelector.RegionSelected += SelectRegion;
        BodySelector.RegionHovered += body => RegionLabel.Text = Loc.GetString($"dl-interaction-panel-body-{body ?? _region}");
        AllRegions.OnPressed += _ => SelectRegion("all");
        Search.OnTextChanged += _ => RefreshActions();
        ClearSearch.OnPressed += _ => Search.SetText("", true);
        FavoritesOnly.OnPressed += _ => RefreshActions();
        StopButton.OnPressed += _ => RepeatRequested?.Invoke("", false, Interval);
        Speed.Value = InteractionPanelActions.ClampInterval(interval);
        Speed.OnValueChanged += _ => UpdateSpeed();
        Speed.OnReleased += _ =>
        {
            PreferencesChanged?.Invoke();
            foreach (var id in _repeating.ToArray()) RepeatRequested?.Invoke(id, true, Interval);
        };
        UpdateSpeed();
        SelectRegion("all");
    }

    public void SetStatus(InteractionPanelStatusEvent status)
    {
        _repeating.Clear();
        _repeating.UnionWith(status.Repeating);
        StatusLabel.Text = Loc.GetString(status.Message);
        if (_repeating.Count > 0) StatusLabel.Text += " — " + string.Join(", ", _repeating.Select(id => _definitions.FirstOrDefault(a => a.Id == id) is { } action ? ActionName(action) : id));
        StopButton.Disabled = _repeating.Count == 0;
        RefreshActions();
    }

    private static string ActionName(InteractionPanelActionDefinition action) => action.Title ?? Loc.GetString($"dl-interaction-panel-action-{action.Id}");

    public void SetLibrary(InteractionPanelLibraryEvent data)
    {
        _definitions = _standardActions.Concat(data.Actions.Select(a => a.Definition())).ToArray();
        _available.RemoveWhere(id => id.StartsWith("custom:", StringComparison.Ordinal));
        _available.UnionWith(data.Available);
        CustomEditor.SetLibrary(data);
        RefreshActions();
    }

    private void UpdateSpeed() => SpeedLabel.Text = Loc.GetString("dl-interaction-panel-interval", ("seconds", Interval.ToString("0.0", System.Globalization.CultureInfo.CurrentCulture)));

    private void SelectRegion(string body)
    {
        _region = body;
        BodySelector.Selected = body;
        RegionFilter.SelectId(Array.IndexOf(InteractionPanelBodySelector.Regions, body));
        RegionLabel.Text = Loc.GetString($"dl-interaction-panel-body-{body}");
        RefreshActions();
    }

    private void RefreshActions()
    {
        ActionList.RemoveAllChildren();
        var query = Search.Text.Trim();
        var actions = _definitions.Where(a => a.Supports(_self, _humanoid) && a.SupportsSexes(_userSex, _targetSex))
            .Where(a => _region == "all" || a.Body == _region)
            .Where(a => !FavoritesOnly.Pressed || _favorites.Contains(a.Id))
            .Where(a => ActionName(a).Contains(query, StringComparison.CurrentCultureIgnoreCase))
            .OrderByDescending(a => _favorites.Contains(a.Id)).ToArray();
        CountLabel.Text = Loc.GetString("dl-interaction-panel-count", ("count", actions.Length));
        foreach (var action in actions)
        {
            var card = new PanelContainer { PanelOverride = new InteractionPanelRoundedStyle(InteractionPanelCategoryColors.CardBackgrounds[action.Category], 10, 0) };
            var column = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(9), SeparationOverride = 5 };
            var row = new BoxContainer { SeparationOverride = 6 };
            var run = new InteractionPanelCategoryButton(action.Category)
            {
                Text = ActionName(action), HorizontalExpand = true,
                Disabled = !_available.Contains(action.Id), ToolTip = Loc.GetString("dl-interaction-panel-action-hint")
            };
            run.OnPressed += _ => ActionRequested?.Invoke(action.Id);
            var favorite = new Button { Text = _favorites.Contains(action.Id) ? "★" : "☆", ToolTip = Loc.GetString("dl-interaction-panel-favorite-toggle") };
            favorite.OnPressed += _ =>
            {
                if (!_favorites.Add(action.Id)) _favorites.Remove(action.Id);
                PreferencesChanged?.Invoke();
                RefreshActions();
            };
            var repeat = new Button
            {
                Text = Loc.GetString(_repeating.Contains(action.Id) ? "dl-interaction-panel-stop" : "dl-interaction-panel-repeat"),
                Disabled = !_available.Contains(action.Id)
            };
            repeat.OnPressed += _ => RepeatRequested?.Invoke(action.Id, !_repeating.Contains(action.Id), Interval);
            row.AddChild(run); row.AddChild(favorite); row.AddChild(repeat);
            column.AddChild(row);
            column.AddChild(new Label
            {
                Text = (_humanoid ? Loc.GetString($"dl-interaction-panel-body-{action.Body}") + " · " : "") +
                Loc.GetString($"dl-interaction-panel-category-{action.Category.ToString().ToLowerInvariant()}"), Modulate = InteractionPanelAppearance.MutedText
            });
            card.AddChild(column);
            ActionList.AddChild(card);
        }
        if (actions.Length == 0) ActionList.AddChild(new Label { Text = Loc.GetString("dl-interaction-panel-empty") });
    }
}

