# Imported from Simple-Station/Einstein-Engines, master archive.
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnumLeverRifle
  result: MagazineMagnumLeverRifle
  materials:
    Steel: 185
