# Imported from Simple-Station/Einstein-Engines, master archive.
# Base prototypes

- type: latheRecipe
  id: ShellShotgun
  result: ShellShotgun
  category: Ammo
  completetime: 2
  materials:
    Steel: 20
- type: latheRecipe
  id: ShellShotgunLumen
  result: ShellShotgunLumen
  category: Ammo
  completetime: 2
  materials:
    Plastic: 20
    Steel: 5
    Plasma: 5
- type: latheRecipe
  id: EnergyCutlass
  result: EnergyCutlass
  completetime: 10
  materials:
    Tungsten: 300
    Gold: 300
    Bluespace: 300
    Plasma: 300
    Diamond: 100
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistol
  result: MagazinePistol
- type: latheRecipe
  id: WeaponPistolViper
  result: WeaponPistolViperEmpty
  category: Weapons
  completetime: 6
  materials:
    Aluminum: 900
    Plasteel: 100
    Plastic: 150
    Silver: 100
- type: latheRecipe
  id: WeaponPistolN1984
  result: WeaponPistolN1984Empty
  category: Weapons
  completetime: 6
  materials:
    Steel: 800
    Plasteel: 100
    Plastic: 250
    Gold: 200
    Silver: 100
- type: latheRecipe
  id: MagazineMagnum
  result: MagazineMagnum
  category: Ammo
  completetime: 5
  materials:
    Steel: 150
- type: latheRecipe
  id: WeaponPistolMk58
  result: WeaponPistolMk58Empty
  category: Weapons
  completetime: 6
  materials:
    Aluminum: 800
    Steel: 100
    Plastic: 150
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnum
  result: SpeedLoaderMagnum
  materials:
    Steel: 200
- type: latheRecipe
  id: MagazineUniversalMagnum
  result: MagazineUniversalMagnum
  category: Ammo
  completetime: 5
  materials:
    Steel: 200
- type: latheRecipe
  id: WeaponPistolUniversal
  result: WeaponPistolUniversalEmpty
  category: Weapons
  completetime: 7
  materials:
    Steel: 1000
    Plasteel: 150
    Plastic: 300
    Gold: 200
    Silver: 100
- type: latheRecipe
  id: EnergySword
  result: EnergySword
  completetime: 10
  materials:
    Tungsten: 300
    Gold: 300
    Bluespace: 300
    Plasma: 300
    Diamond: 100
