<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
    <OutputPath>..\bin\Content.MapRenderer\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Content.IntegrationTests\Content.IntegrationTests.csproj" />
  </ItemGroup>
  <Import Project="..\RobustToolbox\Imports\Testing.props" />

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <Import Project="..\RobustToolbox\MSBuild\Robust.Properties.targets" />
</Project>
